/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.sanseyvich;

import com.github.sanseyvich.lib.FailMessagingLibrary;
import org.testng.annotations.*;

import java.io.IOException;

import static org.testng.Assert.*;

public class LibraryTest {
    @Test
    public void onFailReturnsNonEmptyString() throws IOException {
        FailMessagingLibrary classUnderTest = new FailMessagingLibrary();
        assertFalse(classUnderTest.onFail().isEmpty(), "onFail() should return non empty String");
    }

    @Test
    public void onSuccessReturnsNonEmptyString() throws IOException {
        FailMessagingLibrary classUnderTest = new FailMessagingLibrary();
        assertFalse(classUnderTest.onSuccess().isEmpty(), "onSuccess() should return non empty String");
    }
}
