/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.sanseyvich.lib;

public class FailMessagingLibrary {
    public String onFail() {
        return "Oops, the test failed!";
    }
}
